name: theta_analytics
description: Theta Analytics sdk for Flutter
version: 0.0.1
homepage: "https://buildwiththeta.com"
repository: https://github.com/teta-so/theta_analytics
documentation: https://teta.so/flutter-docs
publish: none

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  clear_response:
  light_logger:

  supabase: any
  http: ^0.13.5
  uuid: ^3.0.6
  cross_file:
  device_info_plus: ^8.1.0
  package_info_plus: ^3.0.3
  universal_platform: ^1.0.0+1
  either_dart:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints: ^2.0.1
