name: theta_open_classes
description: Build visual components on demand.
version: 0.0.1
publish_to: none

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  theta_db_flutter:
    git:
      url: https://github.com/teta-so/theta_db_flutter.git
      ref: main

  theta_open_widgets:
    git:
      url: https://github.com/buildwiththeta/buildwiththeta.git
      path: packages/widgets
      ref: main

  projects_db:
    git:
      url: https://github.com/teta-so/projects_db.git
      ref: main

  theta_models:
    git:
      url: https://github.com/buildwiththeta/buildwiththeta.git
      path: packages/models
      ref: main

  theta_rendering:
    git:
      url: https://github.com/buildwiththeta/buildwiththeta.git
      path: packages/rendering
      ref: main

  clear_response:
  light_logger:

  flutter_bloc: ^8.1.2
  flutter_translator: ^0.1.7
  device_frame:
  equatable:
  supabase_flutter: ^1.4.0
  flutter_localization: ^0.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

dependency_overrides:

flutter:
