name: theta_open_widgets
description: Package with all the widgets used in Theta
version: 0.0.16
publish_to: none

scripts:
  gen: "flutter pub run build_runner build --delete-conflicting-outputs --enable-experiment=records,patterns"

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  theta_models:
    git:
      url: https://github.com/buildwiththeta/buildwiththeta.git
      path: packages/models
      ref: main

  theta_design_system:
    git:
      url: https://github.com/buildwiththeta/buildwiththeta.git
      path: packages/DS
      ref: main

  theta_rendering:
    git:
      url: https://github.com/buildwiththeta/buildwiththeta.git
      path: packages/rendering
      ref: main
  
  light_logger:

  # Bloc
  flutter_bloc: ^8.1.2
  equatable: 2.0.3

  # Typography & Icons
  google_fonts: ^4.0.4
  flutter_feather_icons: 2.0.0+1
  material_design_icons_flutter: 5.0.6595
  font_awesome_flutter_named: 1.1.1
  line_icons: 2.0.1
  flutter_staggered_animations: 1.0.0
  feather_icons:
  lottie: ^2.3.2
  gap: any
  after_layout: 1.2.0
  enum_to_string: 2.0.1
  universal_platform: 1.0.0+1
  collection: ^1.17.0
  flutter_box_transform:
  provider: ^6.0.5

dependency_overrides:
  theta_models:
    path: ../models
  theta_design_system:
    path: ../DS
  theta_rendering:
    path: ../rendering

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: 4.6.0
  flutter_gen_runner:
  flutter_lints: ^2.0.1
  build_runner: any  
  built_value_generator: any
  source_gen: any
  analyzer: any
  reflectable: any

flutter:
  assets:
    - assets/images/standard.png
    - assets/images/dark.png
    - assets/images/night.png
    - assets/images/retro.png
    - assets/images/silver.png
    - assets/images/aubergine.png
