name: theta_open_widgets
description: Package with all the widgets used in Theta
version: 0.0.16
homepage:
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  theta_models:
    git:
      url: https://github.com/buildwiththeta/buildwiththeta.git
      path: packages/models
      ref: main

  # Old 'Teta CMS'
  theta_db_flutter:
    git:
      url: https://github.com/teta-so/theta_db_flutter.git
      ref: main

  projects_db:
    git:
      url: https://github.com/teta-so/projects_db.git
      ref: main

  theta_design_system:
    git:
      url: https://github.com/buildwiththeta/buildwiththeta.git
      path: packages/DS
      ref: main

  theta_open_classes:
    git:
      url: https://github.com/buildwiththeta/buildwiththeta.git
      path: packages/open_classes
      ref: main

  theta_rendering:
    git:
      url: https://github.com/buildwiththeta/buildwiththeta.git
      path: packages/rendering
      ref: main

  flutter_polyline_points:
    git:
      url: https://github.com/andreabuttarelli/flutter_polyline_points.git
      ref: web
  
  light_logger:
  clear_response:

  # DB & Services
  supabase_flutter: ^1.4.0
  http: 0.13.5
  socket_io_client: 2.0.0

  # Bloc
  flutter_bloc: ^8.1.2
  equatable: 2.0.3

  # Typography & Icons
  google_fonts: 2.3.3
  flutter_feather_icons: 2.0.0+1
  material_design_icons_flutter: 5.0.6595
  flutter_svg:
  font_awesome_flutter_named: 1.1.1
  line_icons: 2.0.1
  feather_icons: 1.2.0

  # UI
  hovering: 1.0.4
  transition: 2.0.2
  simple_animations: 4.2.0
  flutter_colorpicker: 1.0.3
  focus_detector: 2.0.1
  sa3_liquid: 1.0.1
  flutter_staggered_animations: 1.0.0

  # Share & send
  mailto: 2.0.0
  url_launcher: any
  clipboard: 0.1.3

  # Widgets
  auth_buttons: 2.0.4
  lottie: ^2.3.2
  youtube_player_iframe: 2.3.0
  custom_refresh_indicator: 1.2.1
  liquid_swipe: 2.1.1
  map: 1.0.0
  latlng: 0.1.0
  webview_windows: 0.2.0
  badges: 2.0.3
  flutter_staggered_grid_view: 0.4.1
  paged_vertical_calendar: 1.1.3
  table_calendar: 3.0.7
  tcard: any
  concentric_transition: 1.0.3
  bouncing_widget: 2.0.0
  qr_flutter: 4.0.0
  barcode: 2.1.0
  barcode_widget: 2.0.1
  google_maps_flutter_web: 0.4.0+3
  google_maps_flutter: 2.2.1
  mobile_scanner: 2.0.0
  gap: any
  another_flushbar: 1.12.29

  # Utils
  uuid: 3.0.6
  password_strength: 0.2.0
  tinycolor: 1.0.3
  math_expressions: 2.3.1
  nil: 1.1.1
  after_layout: 1.2.0
  recase: 4.0.0
  version: 2.0.0
  enum_to_string: 2.0.1
  flutter_automation: 2.0.0
  download: 0.0.1+1
  flutter_dotenv: 5.0.2
  cross_file: 0.3.3+1
  profanity_filter: 2.0.0
  file_picker:
  just_audio: 0.9.27
  geolocator: 8.2.1
  image:
  msix: 2.8.18
  universal_platform: 1.0.0+1
  sizer: 2.0.15
  flutter_translator: ^0.1.7

  # Storage
  hive: 2.2.2
  shared_preferences: 2.0.15

  # Payments
  purchases_flutter: any

  # Responsive values / builder
  responsive_builder: ^0.4.3
  easy_debounce: ^2.0.3
  collection: ^1.17.0
  #flutter_stripe:
  #flutter_stripe_web:

  flutter_box_transform:
  styled_widget: ^0.4.1

dependency_overrides:

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: 4.6.0
  flutter_gen_runner:
  flutter_lints: ^2.0.1
  build_runner: any  
  built_value_generator: any
  source_gen: any
  analyzer: any
  reflectable: any

flutter:
  assets:
    - assets/images/standard.png
    - assets/images/dark.png
    - assets/images/night.png
    - assets/images/retro.png
    - assets/images/silver.png
    - assets/images/aubergine.png
