name: theta
description: Integrate cross-platform server-driven UI into your app using the Theta Flutter library.

version: 0.6.0

repository: https://github.com/buildwiththeta/buildwiththeta
homepage: https://buildwiththeta.com
issue_tracker: https://github.com/buildwiththeta/buildwiththeta/issues
documentation: https://docs.buildwiththeta.com

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

scripts:
  gen: "flutter pub run build_runner build --delete-conflicting-outputs"
  pubget: "flutter pub get"
  dryrun: "dart pub publish --dry-run"
  publish: "dart pub publish"

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  theta_analytics: ^0.1.4
  theta_models: ^0.6.0
  theta_rendering: ^0.1.7
  theta_open_widgets: ^0.6.0

  light_logger: ^0.0.3

  device_frame: ^1.0.0
  equatable: ^2.0.3
  either_dart: ^1.0.0
  http: ^1.0.0
  get_it: ^7.6.0
  provider: ^6.0.5
  hive: ^2.2.3
  path_provider: ^2.0.15
  archive: ^3.3.7
  encrypt: ^5.0.1

dependency_overrides:
  theta_models:
    path: ../models
  theta_open_widgets:
    path: ../widgets
  theta_rendering:
    path: ../rendering

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner: any

flutter: